
#########################################################
# Documents the conda packages required for TAP-build
#
#  This environment builds upon the PyGNOME environment 
#  (excluding _build, _test, _docs packages) and includes 
#  packages for post_gnome as well
#
# USE:
#   conda env create -n gnome_tap --file requirements.yaml
#
# After, install pygnome in this environment
#   $ conda activate gnome_tap
#   $ cd ../pygnome/py_gnome
#   $ git checkout develop 
#   $ python -m pip install ./
# OR (for editable version)
#   $ pip install --no-build-isolation -e ./ 
#  
# NOTE: This file requires the user to have a git token and 
#       will prompt user for the password during install
#
# To avoid need for Git token, comment out `-pip:` section 
# and, within the gnome_tap environment, clone and install 
# (1) tap-build and (2) post-gnome to their own directories:
#   $ git clone ssh://git@gitlab.orr.noaa.gov:9933/gnome/tap/tapbuild.git
#   $ cd tapbuild
#   $ pip install -e ./
#   $ cd ../
#   $ git clone ssh://git@gitlab.orr.noaa.gov:9933/gnome/post_gnome.git
#   $ cd post_gnome 
#   $ pip install -e ./
#  
# Now you can start tap dancing!
#########################################################

name: gnome_tap

channels:
- conda-forge

dependencies:
- python=3.12
- scikit-build-core
- cmake=3.15

## System libs
- colander <2
- progressbar
- psutil
- python-dateutil
- pyzmq
# Needed for multiprocessing, which is currently broken
# pyzmq
# tornado
# tblib

## Base numerical libs
- numpy
- scipy

# File I/O
- xarray
- netCDF4
- pyyaml # post_gnome

## Modeling libs
- gsw
- trimesh
 
## Spatial Libs
- geojson
- geopandas
- mapbox_earcut
- pyogrio
- pyproj
- shapely

# NOAA maintained packages
- gridded
- pynucos
- cell_tree2d
- py_gd
- adios_db

# Required to build PyGNOME and TAP_build
# NOTE: you also need a compiler set up to build Python extensions
- cython
- setuptools  # older versions uses different build dirs
- gitpython

## TAP libs
- bumpversion
- wheel
- watchdog
- flake8
- tox
- coverage
- Sphinx
- pyshp # post_gnome
- pytest # post_gnome

## Graphics/development
- cartopy # post_gnome
- matplotlib # post_gnome
- Jupyter 

## Package installs
- pip
- pip:
   - -e git+https://${USER}@gitlab.orr.noaa.gov/gnome/tap/tapbuild.git#egg=tapbuild
   - git+https://${USER}@gitlab.orr.noaa.gov/gnome/post_gnome.git
# pygnome install can't be done in this way because of "_" in `py_gnome` subdirectory. 
#   - git+https://${USER}@gitlab.orr.noaa.gov/gnome/pygnome.git#egg=py_gnome&subdirectory=py_gnome

